### PR TITLE
Added 'Snapshot', 'Z Report' in the 'Configuration'.

### PR DESCRIPTION
**Pull request by werim**
Snapshot: gets Account Snapshot from Binance API. That needs some visual improvements. Any help will be persiaded.
Z report: Shows last 10 trades that have written to database.

### CODE REVIEW

**Comment by lorcalhost** [comment]
Thanks for your contribution @werim ,
I will review it later 😄

**Comment by lorcalhost** [comment]
Hi @werim , I checked your PR and prettyfied the Binance snapshot button a bit.  
I am unsure of the purpose of the `Z Report` button tho.  

What advantages does it have over the "Trade history" function?

**Comment by werim** [comment]
> I believe that information is not relevant to people when they look at their trade history.  
> 
> Why would you want to see the price of that amount now if the trade happened two days ago?  
> 
> The `Trade History` button already provides information about the change in price from buy and sell orders.
> 
> 
> 
> Your Z Report button:
> 
> ```
> 
> DENT               2021-04-06 14:02:06.243558
> 
> Exchange rate when BOUGTH:
> 
> 0.0153 DENT/USDT
> 
> Current exchange rate:
> 
> 0.0099 DENT/USDT
> 
> Current value:
> 
> 42.4752 
> 
> Change:
> 
> -35.25%
> 
> ```
> 
> 
> 
> Current `Trade History` button:
> 
> ```
> 
> 14:02:06 06/04/2021
> 
> Bought 4216 DENT for 64.605984 USDT
> 
> Status: COMPLETE
> 
> ```
> 
> 
> 
> 

You're right I need to see the price when bought and in binance hard to find price u bought.

**Comment by werim** [comment]
When I first pressed panic button I wanted to see all coin's I have, not the last trade. In Z report I want to learn if they made profit or not.

**Comment by werim** [comment]
Without float() the if condition doesnt work

**Comment by lorcalhost** [comment]
> When I first pressed panic button I wanted to see all coin's I have, not the last trade. In Z report I want to learn if they made profit or not.

Using the `Trade History` button you can check if your trades made any profit.  
To see all coins you have I guess the `Binance Snapshot` button can be used.  
  
I believe the `Z Report` button can be removed and only the `Binance Snapshot` function can make it into the `main` branch after some tweaking.

**Comment by titulebolide** [comment]
Hello,

The snapshot functionnality has finally been implemented in another way for the graph visualisation. I think this PR should not be merged at the end. What do you think @DmytroLitvinov ?

@werim thanks a lot for your work though!

**Comment by DmytroLitvinov** [comment]
Totally agree with you @titulebolide. I would not merge it for sure because it is outdated for now. And as a result, I would close it.

**Pull request closed without merging**
