### PR TITLE
added exchange ratio and current price

### PR DESCRIPTION
**Pull request by bloodf**
added exchange ratio and current price

Added the current price and exchange ratio in the Current Value options

image

### CODE REVIEW

**Comment by lorcalhost** [comment]
I don't believe this actually works for everyone, not all people are using `USDT` as bridge currency.  
From my understanding Binance Trade Bot handles prices a bit weirdly in its database:
- `balance` is the amount of current coin
- `usd_price` is the price in USD
- `buy_price` is the buy price in bridge currency
</br>
Feel free to correct me if I'm wrong

**Comment by bloodf** [comment]
I'm using  the  handlers for the bridge in the calculations, so don't matter the bridge, it will be always the same ratio.

**Comment by lorcalhost** [comment]
Upon closer inspection there are a few problems in your PR.
```
Current Price in *{bridge}*: `{round(((balance * usd_price) / balance), 6)}`
```
Problems with this:
- Why multiply and divide by the same value? `(balance * usd_price) / balance` is equal to `usd_price`
- Current price is not in bridge currency but in USD

The corrected string would be:  
```
Current Price in *USD*: `{round(usd_price, 6)}`
```
</br>

Also, 
```
_Exchange ratio_ {round((buy_price / balance), 6)} *{bridge}/{current_coin}*
```
With this phrasing people might believe this is the current exchange ratio while what you are trying to do is show the the exchange ratio when the coin was purchased.  
It might be better to have a message similar to 
```
_Initially bought for_ {round(buy_price, 2)} *{bridge}* (`{round((buy_price / balance), 6)}` *{bridge}/{current_coin}*)
```

**Comment by bloodf** [comment]
@lorcalhost yeah, I've made this PR just for the Ideas, it was done poorly I know I will re-do it with better formatting.

**Comment by lorcalhost** [comment]
I will close this PR and change those strings in PR #30 
PR #30 is a complete codebase refactoring and it's going to be released very soon :)

**Pull request closed without merging**
