### PR TITLE
GBP values plus modifying change in value percentage calculation 

### PR DESCRIPTION
**Pull request by shanejones**
- Added an approximate GBP to "Current Values" button output 
- Added an approximate GBP to "Progress" button output
- Changed "Change in value" to be calculated from the coin values and not the overall value of the portfolio

### CODE REVIEW

**Comment by lorcalhost** [comment]
Hi @shanejones , thanks for the contribution.  
I believe the price in GBP is not relevand to every `BTB-manager-telegram` user.  
This being said a feature with which users can choose their currency could be implemented.  

Also: conversion rates shouldn't be hard coded but fetched from an API.

**Comment by shanejones** [comment]
Hey @lorcalhost 

I could make this an optional setting to define a users home currency and then pull the rates for that currency.

**Comment by karl0ss** [comment]
I may have just solved the "worry" in my PR

**Comment by titulebolide** [comment]
As @lorcalhost, I find this pr inappropriate, given also the fact that the change is hard-coded.

I propose to cancel this PR if everybody agrees.

**Comment by DmytroLitvinov** [comment]
Agree.

**Pull request closed without merging**
