### PR TITLE
Update buttons.py

### PR DESCRIPTION
**Pull request by ludmildev**
Adding current coint can be converted to the initial one

### CODE REVIEW

**Comment by titulebolide** [comment]
Hello, thanks for your PR.
In my understanding, this is exactly what tells the profit expressed in the start coin.
What do this provides?

**Comment by ludmildev** [comment]
Hello,

you will be able to see the amount of profit/loss from the current coin compared to the inital one. For example if you have started with BTC and now the bot owns ETH, you will be able to see the amount of BTC if you sell your ETH now.

**Comment by titulebolide** [comment]
Hey, thanks for pushing everything here.
Actually this would be very redundant with the profit data
I explain:
If i started with 5 BTC, and now I have 8 ETH, that can be converted into 6 BTC, the profit will show something like Profit : +20% BTC

**Comment by ludmildev** [comment]
Hey, well it will show you the amount of BTC too. 

Now you can see the % of profit but not the actual amount:
Start Coin: 5 BTC - Profit +20%
 
It will add the information as it is:
ETH can be converted to 6 BTC

So you can see the % profit and the amount now, instead of make calculations. :)

**Comment by titulebolide** [comment]
I've understood that however I keep standing on my point that this is a redundant piece of information and I'd like to keep all the messages sent back by the bot as clear as possible. However this opinion might be whack and I would be happy to hear what @ullasbharadwaj and @DmytroLitvinov think about that!

**Comment by DmytroLitvinov** [comment]
I agree with @titulebolide.

I want to add - if it is requested by the community in our Discord server - I would merge it.

**Comment by ullasbharadwaj** [comment]
I agree with @titulebolide . However, this calculation of the current equivalent value of the Start coin is already present in the code. Lin kto it (from PR #221 )  
https://github.com/lorcalhost/BTB-manager-telegram/blob/07919f88993c05d7721d9febb771f3aac287bce2/btb_manager_telegram/buttons.py#L668

You can print it in profits if it's a fan favourite ;-)
Bot profit: X% USD / Y% Coin (+- ActualCoinValue)

**Pull request closed without merging**
