### PR TITLE
add error handing for bot_stats button

### PR DESCRIPTION
**Pull request by ullasbharadwaj**
added basic error handling to show User what went wrong while displaying the bot stats

### CODE REVIEW

**Comment by titulebolide** [comment]
Besides the function I talked in my review, it's a pretty good thing overall you brought here.
However, it's conflicting with the way errors are currently handled in other functions (see the way graphs errors are handled) : the trace back is simply sent to the user since we don't expect him to debug himself the problem. Creating a custom error message can be a bit "bloated"?
Let me know your opinion on this

**Comment by ullasbharadwaj** [comment]
So you are suggesting we need to use Try-Catch blocks for every error handle? It means we will have common error message with exception such as Index out of range. But how do you indicate where it actually went wrong? (debugging would become difficult). What do you think?

**Comment by titulebolide** [comment]
Nope, I'm talking about a big ass try statement that handles the whole function and the except just throws "an error happened while trying to get bot stats. Log :" and you dump the log. Of course this is acceptable only if the common cases of failures (such as brand new databases or no trades yet) are gracefully handled

**Comment by ullasbharadwaj** [comment]
I have fixed some critical issues and added some features.
1. Support for BTC Bridge
2. Get current USDT price for Start Coin and Current Coin directly from binance instead of scout history
3. rename variables for understanding
4. Slightly modified the print output

I tested Databases of all 4 combinations of start coin and current coin being BTC and USDT.
Kindly test and let me know your opinion.

I couldn't find time for fixing error handling as you suggested.

**Comment by titulebolide** [comment]
So, you're hardcoding BTC? It's not really what we're looking for I think...

**Comment by ullasbharadwaj** [comment]
I am adding support for BTC as a Bridge. To consider any bridge such as BNB, we can take it from here.

**Comment by titulebolide** [comment]
From here? From what?
The idea is not to have to add any new support, but to support every single bridge whatsoever.

I'd suggest using the report values instead of the database.

**Comment by ullasbharadwaj** [comment]
Thanks for the suggestion. I have generalized the bot stats to work with any bridge.
I found it is easy and meaningful by sticking the bot stats calculations to the bridge of the very first trade.
I have a stripped many things and the code is very simple and tidy. Have a look and let me know.

**Comment by titulebolide** [comment]
Thanks for the updates, I'll check it soon. What do you think of using the reports such as done in #219?

**Comment by ullasbharadwaj** [comment]
Its also a neat idea, but I thought its just couple of api calls with get_current_price, so i just used that.

**Comment by titulebolide** [comment]
Yes using get_current_price is ok, but I don't know how you get the price of BTC (if BTC is the bridge) at the beggining of the bot ?

**Comment by titulebolide** [comment]
Btw, what is this for : https://github.com/lorcalhost/BTB-manager-telegram/blob/c40425dc5f8285afba6f2f9ea127b4a7f01919f3/btb_manager_telegram/buttons.py#L529
Are you retreiving the whole woin list? because it is already available under settings.COIN_LIST

**Comment by titulebolide** [comment]
Btw, may I push changes to this branch or do you want me to open up a new branch to suggests some changes?

**Comment by ullasbharadwaj** [comment]
You can push the changes, now worries.  
And regarding coinList, yes you are right, its a redundant code.I was not aware of settings.

**Comment by titulebolide** [comment]
Thanks! I'll take a look into that

**Comment by titulebolide** [comment]
It's ready for testing, and I merge it if you're happy with it

**Comment by titulebolide** [comment]
@all-contributors please add @ullasbharadwaj for bug

**Pull request merged**
