### PR TITLE
Dutch language file

### PR DESCRIPTION
**Pull request by phoenix-blue**
Added the Dutch translation files

### CODE REVIEW

**Comment by MasaiasuOse** [comment]
Update the main.py line 59 😀

**Review by MasaiasuOse — APPROVED** [review]
Looks better

**Comment by titulebolide** [comment]
Yay that's excellent! Thank you!

**Comment by titulebolide** [comment]
@all-contributors please add @MasaiasuOse for translation

**Comment by titulebolide** [comment]
and here also
@all-contributors please add @phoenix-blue for translation

**Pull request merged**
