### PR TITLE
Add the ability to have a second currency on the list

### PR DESCRIPTION
**Pull request by karl0ss**
Uses a new config/custom.json file (example included) to allow user to pass in a second currency, that will be listed under the default one

e.g.

Current coin XLM:
 - Balance: 55.8461 XLM
 - Exchange rate purchased: 0.3394 USDT/XLM 
 - Exchange rate now: 0.3375 USD/XLM
 - Change in value: 0.97 %
 - Value in USD: 18.85 USD
 - Value in GBP: 13.7 GBP
 - Value in BTC: 0.0003993 BTC

Will default back to not show the message, if either turned off via the custom.json or the custom.json file has not been created.

### CODE REVIEW

**Comment by lorcalhost** [comment]
Hey @karl0ss @QuentinLuppo , thanks for the contribution.
This feature was very much needed.
Let me know when you think the PR is stable and I'll test it out 👍

**Comment by karl0ss** [comment]
No problems, I seem to be getting issues from Forex for the conversion at the moment, has been working fine,but just blew up, so I closed the pr, when I get this working, I'll reopen it.

**Comment by QuentinLuppo** [comment]
hello, yes forex got issues: https://github.com/MicroPyramid/forex-python/issues/100
I don't know when forex will fix it ... I have work around for this in my code

**Comment by QuentinLuppo** [comment]
maybe if we got the same problem in futur we can store last knowledge value EUR/GBP  in the db ?

**Comment by QuentinLuppo** [comment]
https://theforexapi.com/ work now issue fixed

**Comment by karl0ss** [comment]
Yeah your correct, it does now seem to be working again, i'm a little concerned that it will cause instability with the bot, so im going to take a look at a different service, or just make it "fallback" to no 2nd currency if the forex call fails, will have a look once my kids are in bed, thinking i will change custom.json, to settings.json, that way it could be extended for other bits as well (i see a branch with the TZ stuff in there, so that could be a good idea for both)

**Comment by karl0ss** [comment]
Have updated this a bit, and have moved all the forex related activities into the utils file, also, reworked it so that if the forex call fails, it will not cause the message to fail, as was the case before, it will now return both intended messages "Current Val and Progess" and will just include a "Forex Error" line where the conversion would have taken place, i do like @QuentinLuppo  idea of storing the last known value, but it could end up being very old, and that would annoy me, i'd rather know that it was not working, and if didn't for long enough, id probably fix it anyway..

**Comment by karl0ss** [comment]
Noticed the TZ stuff wasn't set for all "times" displayed by the bot, so updated that and converted it to a one liner, also refactored the messages for Current Val and Progress, so I can insert the extra currency better, and remove all the duplication.

This is probably ready for you now @lorcalhost

**Comment by QuentinLuppo** [comment]
Hello @karl0ss,
I don't convert all the date in my last commit beacause some dates were true. See my picture who came from your version : (crurent date from my mobile phone) 
Screenshot_20210902-152027_Telegram
Can you fix it ? If it is that.. 
Only for trades date who come from database who are stored in utc i think.

**Comment by QuentinLuppo** [comment]
Screenshot_20210902-152027_Telegram

**Comment by karl0ss** [comment]
Interesting, where are you? As I am in UK, and have set the TZ to Europe/London, as per the default in your app, and all the times line up with my phone time..

**Comment by QuentinLuppo** [comment]
Strange .... I am in France and have set the TZ to Europe/Paris. Do you know where the value of last_update come from ? Storage in the db or create with function SQL ?

**Comment by karl0ss** [comment]
@QuentinLuppo I set my tz to Europe/Paris and it pushed my time on +1 h as expected

**Comment by karl0ss** [comment]
This all seems to be working ok for me now, I have also added the ability for it to pull in your total wallet balance from binance, in your converted currency, the example has it switched off by default.

**Comment by QuentinLuppo** [comment]
Hello, I found why i get this error. My raspberry was set to local time zone and this has the effect to storage it in the database... So timezone is working for me now. Nice idea for balance function ! One of my friend want it like me ! Thank you for this

**Comment by QuentinLuppo** [comment]
After test your balance function, i got this exception : APIError(code=-1121): Invalid symbol.
Using this settings : 
{
    "Custom_Currency_Enabled": 1,
    "Currency": "EUR",
    "Custom_Timezone_Enabled": 1,
    "Timezone": "Europe/Paris",
    "Total_Binance_Wallet_Balance": 1
}

**Comment by karl0ss** [comment]
@QuentinLuppo I will add busd to my exception, i had to do it for USDT as well, as you can't convert that to USD, so my calculation is a little bit off...

**Comment by karl0ss** [comment]
@QuentinLuppo i think that should fix it, i don't have BUSD to check...

**Comment by karl0ss** [comment]
This pr is getting quite large with too many changes...not too sure if it should be abandoned, and i will see if i can make some smaller pr's..

This will not also show your binance total wallet value, and the converted balances of all the coins held....

This call takes longer than the normal Current Value call, so gets sent as a second message after the Current Value one, when the information is ready.

**Comment by titulebolide** [comment]
Hi there, 

i've went through your code and I'm not sure if it should be merged into the bot for the following reasons:
- You retreive the binance api keys from the trade bot to initiate a binance api instance to retreive data, which is now already done in the file `btb_mananger_telegram/report.py` and we should avoid this
- For now we try to avoid the use of config file and give priority to command line options and flags (e.g. the flag --currency that is now existing, alongside with the flag --oer_keys which provides an openexchange rate key to have the exchange rate between USD and GBP for example)
- Your code contains some mistakes (for example, line 156 to 165 of `btb_manager_telegram/buttons.py` the lack of coma is intentional)

For theses reasons, i think it is for the best to abandon this PR. However, your project is still doable and even more easily doable since report.py is providing tools that you can use to add an new currency.

@DmytroLitvinov what do you think?

@karl0ss and @QuentinLuppo thanks a lot for your work though, if you want we can work together on a new PR to bring this project on upstream. Let me know

**Comment by QuentinLuppo** [comment]
Hello,

You're right, i will see your new code this week-end for update myself :')
Moreover, the balance function isn't working maybe since the Boba token airdrop.
I can try this weekend to code and test new features on my Raspberry

**Comment by titulebolide** [comment]
Nice, then i close this PR for now. Thanks for your answer!

**Pull request closed without merging**
