### PR TITLE
Wrong Coin is displayed in current value

### PR DESCRIPTION
**Pull request by MasaiasuOse**
The ex. rate stored in the db is coin/USDT and not coin/bridge. The best solution is too display it as USD as `binance.us` doesn't have USDT

### CODE REVIEW

**Comment by titulebolide** [comment]
Err... I read the code from the binance trade bot, it's a mess...

For `exchange_rate_purchased`, the rate is set at `buy_price` line 152 of `buttons.py`, which is taken from the column `crypto_trade_amount` from `trade_history`

`trade_history` being a table build by sqlalchemy in `binance_trade_bot/models/trade.py`, whose column `crypto_trade_amount` is set by the method `TradeLog::set_complete(crypto_trade_amount)` in `binance_trade_bot/database.py`

The said method is called by `BinanceApiManager::_buy_alt` and `BinanceApiManager::_sell_alt` in `binance_trade_bot/binance_api_manager.py` as : `trade_log.set_complete(order.cumulative_quote_qty)`. Where order is the return of the method `BinanceApiManager::self.wait_for_order`. `wait_for_order` returns an object of type `BinanceOrder`.

`BinanceOrder` is defined  in `binance_stream_manager.py` and its init is:
```python
def __init__(self, report):
        self.event = report
        self.symbol = report["symbol"]
        self.side = report["side"]
        self.order_type = report["order_type"]
        self.id = report["order_id"]
        self.cumulative_quote_qty = float(report["cumulative_quote_asset_transacted_quantity"])
        self.status = report["current_order_status"]
        self.price = float(report["order_price"])
        self.time = report["transaction_time"]
        self.cumulative_filled_quantity = float(report["cumulative_filled_quantity"])
```

Such objects are created in `binance_stream_manager.py` by `_process_stream_data`, which receives a `stream_data`, which is the raw data from the websocket api from binance. In the case where the type of the stream_data is an execution_report, the key `cumulative_filled_quantity` of the BinanceOrder is filled to the raw value of the websocket stream. The websocket api gives as example:
```
{
  "e": "executionReport",        // Event type
  "E": 1499405658658,            // Event time
  "s": "ETHBTC",                 // Symbol
  "c": "mUvoqJxFIILMdfAW5iGSOW", // Client order ID
  "S": "BUY",                    // Side
  "o": "LIMIT",                  // Order type
  "f": "GTC",                    // Time in force
  "q": "1.00000000",             // Order quantity
  "p": "0.10264410",             // Order price
  "P": "0.00000000",             // Stop price
  "F": "0.00000000",             // Iceberg quantity
  "g": -1,                       // OrderListId
  "C": "",                       // Original client order ID; This is the ID of the order being canceled
  "x": "NEW",                    // Current execution type
  "X": "NEW",                    // Current order status
  "r": "NONE",                   // Order reject reason; will be an error code.
  "i": 4293153,                  // Order ID
  "l": "0.00000000",             // Last executed quantity
  "z": "0.00000000",             // Cumulative filled quantity
  "L": "0.00000000",             // Last executed price
  "n": "0",                      // Commission amount
  "N": null,                     // Commission asset
  "T": 1499405658657,            // Transaction time
  "t": -1,                       // Trade ID
  "I": 8641984,                  // Ignore
  "w": true,                     // Is the order on the book?
  "m": false,                    // Is this trade the maker side?
  "M": false,                    // Ignore
  "O": 1499405658657,            // Order creation time
  "Z": "0.00000000",             // Cumulative quote asset transacted quantity
  "Y": "0.00000000",             // Last quote asset transacted quantity (i.e. lastPrice * lastQty)
  "Q": "0.00000000"              // Quote Order Qty
}
``` 

Thus the `rate` is the value `cumulative fillet quantity` that might be expressed as the rate COIN1/COIN2 and not COIN/USD ?

**Comment by MasaiasuOse** [comment]
You are correct. I made a mistake, but the old is defintitly wrong too:

> Current coin ATOM:
>  - Balance: 5.28471 ATOM
>  - Exchange rate purchased: 0.0004687 BTC/ATOM
>  - Exchange rate now:           27.36 USD/ATOM
>  - Change in value: 5831492.29 %
>  - Value in USD: 144.59 USD
>  - Value in BTC: 0 BTC
> 
> Bought for 0 BTC
> 1 day change BTC: 0 %
> 7 day change BTC: 0 %<

We compare two different kinds of values

**Comment by titulebolide** [comment]
You go then to change this line : https://github.com/lorcalhost/BTB-manager-telegram/blob/a16c6248cc71eb88ebbab5f082a67dc8b2cf871f/btb_manager_telegram/buttons.py#L225
However I'm still unsure about that because the SQL request is : https://github.com/lorcalhost/BTB-manager-telegram/blob/a16c6248cc71eb88ebbab5f082a67dc8b2cf871f/btb_manager_telegram/buttons.py#L191
And coin[2] (which is the amount here corresponds to what's called priceInUSD, but it's still the same column `crypto_trade_amount`. Btw, i did a mistake, this column represents the value 'Cumulative quote asset transacted quantity', and i have no idea what it means.

Also, `27.36 USD/ATOM` should be more like `27.36 ATOM/USD` ?

**Comment by MasaiasuOse** [comment]
[This](https://dev.binance.vision/t/beginners-guide-to-quoteorderqty-market-orders/404) explains the quote asset. The coin pairs consists of a base asset and a quote asset. When we look at BTC/USDT, BTC is the base asset and USDT is the quote asset.
In our case it is the cummulative transacted bridge amount

And yeah I think so to the "base" asset has to first and then the quote asset

**Pull request closed without merging**
